In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

data = pd.read_csv ('/Users/alisha/Downloads/movies_dataset.csv')

In [2]:
data

,Unnamed: 0,IMDb-rating,appropriate_for,director,downloads,id,industry,language,posted_date,release_date,run_time,storyline,title,views,writer
0,0,4.8,R,John Swab,304,372092,Hollywood / English,English,"20 Feb, 2023",Jan 28 2023,105,Doc\r\n facilitates a fragile truce between th...,Little Dixie,"2,794",John Swab
1,1,6.4,TV-PG,Paul Ziller,73,372091,Hollywood / English,English,"20 Feb, 2023",Feb 05 2023,84,Caterer\r\n Goldy Berry reunites with detectiv...,Grilling Season: A Curious Caterer Mystery,"1,002",John Christian Plummer
2,2,5.2,R,Ben Wheatley,"1,427",343381,Hollywood / English,"English,Hindi","20 Apr, 2021",Jun 18 2021,1h 47min,As the world searches for a cure to a disastro...,In the Earth,"14,419",Ben Wheatley
3,3,8.1,NaN,Venky Atluri,"1,549",372090,Tollywood,Hindi,"20 Feb, 2023",Feb 17 2023,139,The life of a young man and his struggles agai...,Vaathi,"4,878",Venky Atluri
4,4,4.6,NaN,Shaji Kailas,657,372089,Tollywood,Hindi,"20 Feb, 2023",Jan 26 2023,122,A man named Kalidas gets stranded due to the p...,Alone,"2,438",Rajesh Jayaraman
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20543,20543,NaN,NaN,NaN,"1,998",28957,Bollywood / Indian,Hindi,"01 Jan, 1970",Mar 13 1959,NaN,NaN,Bhai-Bahen,"6,219",NaN
20544,20544,7.7,NaN,Bimal Roy,"6,080",28958,Bollywood / Indian,Hindi,"01 Jan, 1970",May 13 1955,159,Devdas and Parvati had been inseparable as chi...,Devdas,"16,376","Rajinder Singh Bedi, Saratchandra Chatterjee, ..."
20545,20545,8.0,NaN,NaN,"3,276",30459,Bollywood / Indian,Hindi,"01 Jan, 1970",Mar 28 1958,1h 50min,"While driving his car on a rainy night, Anand'...",Madhumati,"7,220",NaN
20546,20546,NaN,NaN,NaN,309,371669,Wrestling,English,"10 Feb, 2023",Feb 09 2023,NaN,NaN,TNA.Impact 2023-02-09,"1,419",NaN
20547,20547,NaN,NaN,NaN,"2,613",371816,Wrestling,English,"14 Feb, 2023",Feb 13 2023,NaN,NaN,WWE Raw 2023-02-13,"6,697",NaN

In [3]:
count_of_missing_values=data.isna().sum()  
pd.DataFrame(data.isna().sum())

                    0
Unnamed: 0          0
IMDb-rating       841
appropriate_for  9476
director         1938
downloads           1
id                  0
industry            1
language          542
posted_date         1
release_date        1
run_time         1768
storyline        1701
title               1
views               1
writer           2192

In [4]:
total_values = np.product(data.shape)
numerator = count_of_missing_values.sum()
miss_p  = (numerator/ total_values)*100
print(" The percentage of missing values from the dataset is :", miss_p)

 The percentage of missing values from the dataset is : 5.990526247485562

# Data Cleaning and Preperation

In [6]:
data['IMDb-rating']=data['IMDb-rating'].fillna(np.mean(data['IMDb-rating']))

data['appropriate_for']=data['appropriate_for'].fillna('Unrated')

data['appropriate_for'] =data['appropriate_for'].replace('Not Rated', 'Unrated')

data['views']=data['views'].fillna('0')
data['views'].isnull().sum()
data['views'] = data['views'].apply(lambda x:(x.replace(',', ''))).astype(int)

In [7]:
data['title'].value_counts()

Vaathi                                           402
Who Invited Charlie?                             402
The Girl Who Escaped: The Kara Robinson Story    402
Little Dixie                                     202
Consent                                          202
                                                ...
Beyond Valkyrie: Dawn of the 4th Reich             1
Loaded                                             1
3096 Days                                          1
Sex, Death and Bowling                             1
A Haunted House                                    1
Name: title, Length: 16572, dtype: int64

In [8]:
counts = data['title'].value_counts()
counts = counts[counts>76]

duplicate_titles=counts.index.tolist()
duplicate_titles

['Vaathi',
 'Who Invited Charlie?',
 'The Girl Who Escaped: The Kara Robinson Story',
 'Little Dixie',
 'Consent',
 'The Inspection',
 'WWE Smackdown 2023-02-10',
 'Vacation Home Nightmare',
 'Shehzada',
 'Carnifex',
 'Marlowe',
 'Baby Ruby',
 'Your Place or Mine',
 'WWE Raw 2023-02-13',
 'TNA.Impact 2023-02-09']

In [9]:
import math
def fix_duplicates(df,x):
    y = 0
    temp= []

    y=math.ceil(np.mean(x[x['title']==df]['views']))
    temp=x[x['title']==df].iloc[0]
    print(temp)

    x= x.drop(x[x['title']==df].index)

    x = x.append(temp,ignore_index = True)
    x.loc[x['title'] == df, 'views'] = y
    return x

In [10]:
for i in duplicate_titles:
    data = fix_duplicates(i,data)

Unnamed: 0                                                         3
IMDb-rating                                                      8.1
appropriate_for                                              Unrated
director                                                Venky Atluri
downloads                                                      1,549
id                                                            372090
industry                                                   Tollywood
language                                                       Hindi
posted_date                                             20 Feb, 2023
release_date                                             Feb 17 2023
run_time                                                         139
storyline          The life of a young man and his struggles agai...
title                                                         Vaathi
views                                                           4878
writer                                                  Venky Atluri
Name: 3, dtype: object
Unnamed: 0                                                        41
IMDb-rating                                                      8.8
appropriate_for                                              Unrated
director                                             Xavier Manrique
downloads                                                         75
id                                                            371744
industry                                         Hollywood / English
language                                                     English
posted_date                                             13 Feb, 2023
release_date                                             Feb 03 2023
run_time                                                         101
storyline          Follows\r\n a New York City family hiding out ...
title                                           Who Invited Charlie?
views                                                           1676
writer                                               Nicholas Schutt
Name: 39, dtype: object
Unnamed: 0                                                        28
IMDb-rating                                                      6.6
appropriate_for                                                TV-14
director                                                Simone Stock
downloads                                                        760
id                                                            371877
industry                                         Hollywood / English
language                                                     English
posted_date                                             15 Feb, 2023
release_date                                             Feb 11 2023
run_time                                                          88
storyline          It follows Kara Robinson as she survives an ab...
title                  The Girl Who Escaped: The Kara Robinson Story
views                                                           7430
writer                                                  Haley Harris
Name: 27, dtype: object
Unnamed: 0                                                         0
IMDb-rating                                                      4.8
appropriate_for                                                    R
director                                                   John Swab
downloads                                                        304
id                                                            372092
industry                                         Hollywood / English
language                                                     English
posted_date                                             20 Feb, 2023
release_date                                             Jan 28 2023
run_time                                                         105
storyline          Doc\r\n facilitates a fragile truce between th...
title                                                   Little Dixie
views                                                           2794
writer                                                     John Swab
Name: 0, dtype: object
Unnamed: 0                                                        60
IMDb-rating                                                      5.5
appropriate_for                                              Unrated
director                                               Nadira Amrani
downloads                                                        378
id                                                            371671
industry                                         Hollywood / English
language                                                     English
posted_date                                             10 Feb, 2023
release_date                                             Feb 07 2023
run_time                                                         NaN
storyline          Bold\r\n and authentic drama set at an elite s...
title                                                        Consent
views                                                           4266
writer                                           Emma Dennis-Edwards
Name: 53, dtype: object
Unnamed: 0                                                        14
IMDb-rating                                                      7.1
appropriate_for                                                    R
director                                            Elegance Bratton
downloads                                                        463
id                                                            371991
industry                                         Hollywood / English
language                                                     English
posted_date                                             17 Feb, 2023
release_date                                             Dec 02 2022
run_time                                                          95
storyline          A\r\n young, gay Black man, rejected by his mo...
title                                                 The Inspection
views                                                           5763
writer                                              Elegance Bratton
Name: 12, dtype: object
Unnamed: 0                               55
IMDb-rating                         5.76215
appropriate_for                     Unrated
director                                NaN
downloads                             1,781
id                                   371740
industry                          Wrestling
language                            English
posted_date                    13 Feb, 2023
release_date                    Feb 10 2023
run_time                                NaN
storyline                               NaN
title              WWE Smackdown 2023-02-10
views                                  4736
writer                                  NaN
Name: 47, dtype: object
Unnamed: 0                                                        22
IMDb-rating                                                        5
appropriate_for                                              Unrated
director                                             Lindsay Hartley
downloads                                                        465
id                                                            371936
industry                                         Hollywood / English
language                                                     English
posted_date                                             16 Feb, 2023
release_date                                             Jan 29 2023
run_time                                                         NaN
storyline          When\r\n a woman is attacked in her short term...
title                                        Vacation Home Nightmare
views                                                           5723
writer                                                 John F. Hayes
Name: 19, dtype: object
Unnamed: 0                                                        11
IMDb-rating                                                        9
appropriate_for                                              Unrated
director                                                Rohit Dhawan
downloads                                                     12,954
id                                                            372039
industry                                          Bollywood / Indian
language                                                       Hindi
posted_date                                             18 Feb, 2023
release_date                                             Feb 17 2023
run_time                                                         142
storyline          Bantu\r\n is hated by his father Valmiki since...
title                                                       Shehzada
views                                                          35831
writer               Hussain Dalal, Rohit Dhawan, Trivikram Srinivas
Name: 9, dtype: object
Unnamed: 0                                                        19
IMDb-rating                                                      4.7
appropriate_for                                              Unrated
director                                                 Sean Lahiff
downloads                                                      1,453
id                                                            371943
industry                                         Hollywood / English
language                                                     English
posted_date                                             16 Feb, 2023
release_date                                             Dec 01 2022
run_time                                                          93
storyline          An\r\n aspiring documentarian and two conserva...
title                                                       Carnifex
views                                                          11626
writer                                                Shanti Gudgeon
Name: 15, dtype: object

Unnamed: 0                                                        29
IMDb-rating                                                      6.1
appropriate_for                                                    R
director                                                 Neil Jordan
downloads                                                        283
id                                                            371876
industry                                         Hollywood / English
language                                                     English
posted_date                                             15 Feb, 2023
release_date                                             Feb 15 2023
run_time                                                         110
storyline          In late 1930's Bay City, a brooding, down on h...
title                                                        Marlowe
views                                                           3044
writer              William Monahan, John Banville, Raymond Chandler
Name: 22, dtype: object
Unnamed: 0                                                        43
IMDb-rating                                                        5
appropriate_for                                              Unrated
director                                                   Bess Wohl
downloads                                                        622
id                                                            371674
industry                                         Hollywood / English
language                                                     English
posted_date                                             10 Feb, 2023
release_date                                             Feb 03 2023
run_time                                                          93
storyline          The\r\n tightly scripted world of a vlogger an...
title                                                      Baby Ruby
views                                                           9097
writer                                                     Bess Wohl
Name: 29, dtype: object
Unnamed: 0                                                        42
IMDb-rating                                                      5.7
appropriate_for                                                PG-13
director                                         Aline Brosh McKenna
downloads                                                      2,712
id                                                            371760
industry                                         Hollywood / English
language                                               English,Hindi
posted_date                                             13 Feb, 2023
release_date                                             Feb 10 2023
run_time                                                         109
storyline          Two\r\n long-distance best friends change each...
title                                             Your Place or Mine
views                                                          14638
writer                                           Aline Brosh McKenna
Name: 28, dtype: object
Unnamed: 0                         44
IMDb-rating                   5.76215
appropriate_for               Unrated
director                          NaN
downloads                       2,609
id                             371816
industry                    Wrestling
language                      English
posted_date              14 Feb, 2023
release_date              Feb 13 2023
run_time                          NaN
storyline                         NaN
title              WWE Raw 2023-02-13
views                            6605
writer                            NaN
Name: 28, dtype: object
Unnamed: 0                            63
IMDb-rating                      5.76215
appropriate_for                  Unrated
director                             NaN
downloads                            309
id                                371669
industry                       Wrestling
language                         English
posted_date                 10 Feb, 2023
release_date                 Feb 09 2023
run_time                             NaN
storyline                            NaN
title              TNA.Impact 2023-02-09
views                               1337
writer                               NaN
Name: 41, dtype: object

In [11]:
data

,Unnamed: 0,IMDb-rating,appropriate_for,director,downloads,id,industry,language,posted_date,release_date,run_time,storyline,title,views,writer
0,1,6.400000,TV-PG,Paul Ziller,73,372091,Hollywood / English,English,"20 Feb, 2023",Feb 05 2023,84,Caterer\r\n Goldy Berry reunites with detectiv...,Grilling Season: A Curious Caterer Mystery,1002,John Christian Plummer
1,2,5.200000,R,Ben Wheatley,"1,427",343381,Hollywood / English,"English,Hindi","20 Apr, 2021",Jun 18 2021,1h 47min,As the world searches for a cure to a disastro...,In the Earth,14419,Ben Wheatley
2,4,4.600000,Unrated,Shaji Kailas,657,372089,Tollywood,Hindi,"20 Feb, 2023",Jan 26 2023,122,A man named Kalidas gets stranded due to the p...,Alone,2438,Rajesh Jayaraman
3,5,5.400000,Unrated,Srinivas Gavireddy,746,372088,Tollywood,Hindi,"20 Feb, 2023",Nov 26 2021,131,"Bagaram,\r\n after inheriting his grandfather'...",Anubhavinchu Raja,2940,"Srinivas Gavireddy, Mayukh Adithya"
4,6,5.762151,TV-PG,NaN,"5,332",372059,Wrestling,English,"19 Feb, 2023",Feb 18 2023,200,Undisputed\r\n WWE Universal title: Reigns vs ...,WWE Elimination Chamber,11978,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17181,29,6.100000,R,Neil Jordan,283,371876,Hollywood / English,English,"15 Feb, 2023",Feb 15 2023,110,"In late 1930's Bay City, a brooding, down on h...",Marlowe,3149,"William Monahan, John Banville, Raymond Chandler"
17182,43,5.000000,Unrated,Bess Wohl,622,371674,Hollywood / English,English,"10 Feb, 2023",Feb 03 2023,93,The\r\n tightly scripted world of a vlogger an...,Baby Ruby,9201,Bess Wohl
17183,42,5.700000,PG-13,Aline Brosh McKenna,"2,712",371760,Hollywood / English,"English,Hindi","13 Feb, 2023",Feb 10 2023,109,Two\r\n long-distance best friends change each...,Your Place or Mine,14758,Aline Brosh McKenna
17184,44,5.762151,Unrated,NaN,"2,609",371816,Wrestling,English,"14 Feb, 2023",Feb 13 2023,NaN,NaN,WWE Raw 2023-02-13,6658,NaN
17185,63,5.762151,Unrated,NaN,309,371669,Wrestling,English,"10 Feb, 2023",Feb 09 2023,NaN,NaN,TNA.Impact 2023-02-09,1380,NaN

In [12]:
data.shape

(17186, 15)

In [13]:
import re
def runtime_conversion(runtime):
    if runtime.isdigit():
        return int(runtime)
    else:
        # Define regex to extract numerical values
        hr_pattern = re.compile(r'(\d+)\s*(h|hr|hour)s?')
        min_pattern = re.compile(r'(\d+)\s*(m|min)')

        # Extracting numerical values from the input string
        hrs = 0
        mins = 0
        match = hr_pattern.search(runtime)
        if match:
            hrs = int(match.group(1))
        match = min_pattern.search(runtime)
        if match:
            mins = int(match.group(1))

        # Convert hours to minutes and return the total runtime in minutes
        return hrs * 60 + mins

In [14]:
#Replaced the NaN values with the average run time of movies
data['run_time'] = data['run_time'].fillna('90')

In [15]:
#Convert all the values of run_time to a standard int format
data['run_time'] = data['run_time'].apply(runtime_conversion)

In [16]:
#dropped industry with null value 
data=data.drop(data[data['id']==371111].index, axis=0)

In [17]:
# Dropping the columns director, storyline, writer as we don't require them
data_cleaned = data.drop(['director', 'writer','storyline'], axis=1)

In [18]:
from datetime import datetime
def conv_posted_date(v):
    format_1 = '%d %b, %Y'
    date = datetime.strptime(v,format_1)
    return date
def conv_release_date(v):
    format_1 = '%b %d %Y'
    date = datetime.strptime(v,format_1)
    return date

In [19]:
data_cleaned['posted_date'] = data_cleaned['posted_date'].apply(conv_posted_date)
data_cleaned['release_date'] = data_cleaned['release_date'].apply(conv_release_date)
data_cleaned

,Unnamed: 0,IMDb-rating,appropriate_for,downloads,id,industry,language,posted_date,release_date,run_time,title,views
0,1,6.400000,TV-PG,73,372091,Hollywood / English,English,2023-02-20,2023-02-05,84,Grilling Season: A Curious Caterer Mystery,1002
1,2,5.200000,R,"1,427",343381,Hollywood / English,"English,Hindi",2021-04-20,2021-06-18,107,In the Earth,14419
2,4,4.600000,Unrated,657,372089,Tollywood,Hindi,2023-02-20,2023-01-26,122,Alone,2438
3,5,5.400000,Unrated,746,372088,Tollywood,Hindi,2023-02-20,2021-11-26,131,Anubhavinchu Raja,2940
4,6,5.762151,TV-PG,"5,332",372059,Wrestling,English,2023-02-19,2023-02-18,200,WWE Elimination Chamber,11978
...,...,...,...,...,...,...,...,...,...,...,...,...
17181,29,6.100000,R,283,371876,Hollywood / English,English,2023-02-15,2023-02-15,110,Marlowe,3149
17182,43,5.000000,Unrated,622,371674,Hollywood / English,English,2023-02-10,2023-02-03,93,Baby Ruby,9201
17183,42,5.700000,PG-13,"2,712",371760,Hollywood / English,"English,Hindi",2023-02-13,2023-02-10,109,Your Place or Mine,14758
17184,44,5.762151,Unrated,"2,609",371816,Wrestling,English,2023-02-14,2023-02-13,90,WWE Raw 2023-02-13,6658
17185,63,5.762151,Unrated,309,371669,Wrestling,English,2023-02-10,2023-02-09,90,TNA.Impact 2023-02-09,1380

In [20]:
from scipy import stats
t=data_cleaned.mode()['language'][0]
print(t)

English

In [21]:
data_cleaned['language']=data_cleaned['language'].fillna('English')

In [22]:
data

,Unnamed: 0,IMDb-rating,appropriate_for,director,downloads,id,industry,language,posted_date,release_date,run_time,storyline,title,views,writer
0,1,6.400000,TV-PG,Paul Ziller,73,372091,Hollywood / English,English,"20 Feb, 2023",Feb 05 2023,84,Caterer\r\n Goldy Berry reunites with detectiv...,Grilling Season: A Curious Caterer Mystery,1002,John Christian Plummer
1,2,5.200000,R,Ben Wheatley,"1,427",343381,Hollywood / English,"English,Hindi","20 Apr, 2021",Jun 18 2021,107,As the world searches for a cure to a disastro...,In the Earth,14419,Ben Wheatley
2,4,4.600000,Unrated,Shaji Kailas,657,372089,Tollywood,Hindi,"20 Feb, 2023",Jan 26 2023,122,A man named Kalidas gets stranded due to the p...,Alone,2438,Rajesh Jayaraman
3,5,5.400000,Unrated,Srinivas Gavireddy,746,372088,Tollywood,Hindi,"20 Feb, 2023",Nov 26 2021,131,"Bagaram,\r\n after inheriting his grandfather'...",Anubhavinchu Raja,2940,"Srinivas Gavireddy, Mayukh Adithya"
4,6,5.762151,TV-PG,NaN,"5,332",372059,Wrestling,English,"19 Feb, 2023",Feb 18 2023,200,Undisputed\r\n WWE Universal title: Reigns vs ...,WWE Elimination Chamber,11978,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17181,29,6.100000,R,Neil Jordan,283,371876,Hollywood / English,English,"15 Feb, 2023",Feb 15 2023,110,"In late 1930's Bay City, a brooding, down on h...",Marlowe,3149,"William Monahan, John Banville, Raymond Chandler"
17182,43,5.000000,Unrated,Bess Wohl,622,371674,Hollywood / English,English,"10 Feb, 2023",Feb 03 2023,93,The\r\n tightly scripted world of a vlogger an...,Baby Ruby,9201,Bess Wohl
17183,42,5.700000,PG-13,Aline Brosh McKenna,"2,712",371760,Hollywood / English,"English,Hindi","13 Feb, 2023",Feb 10 2023,109,Two\r\n long-distance best friends change each...,Your Place or Mine,14758,Aline Brosh McKenna
17184,44,5.762151,Unrated,NaN,"2,609",371816,Wrestling,English,"14 Feb, 2023",Feb 13 2023,90,NaN,WWE Raw 2023-02-13,6658,NaN
17185,63,5.762151,Unrated,NaN,309,371669,Wrestling,English,"10 Feb, 2023",Feb 09 2023,90,NaN,TNA.Impact 2023-02-09,1380,NaN

In [23]:
count_of_missing_values=data_cleaned.isna().sum()  
pd.DataFrame(data_cleaned.isna().sum())

                 0
Unnamed: 0       0
IMDb-rating      0
appropriate_for  0
downloads        0
id               0
industry         0
language         0
posted_date      0
release_date     0
run_time         0
title            0
views            0